

package com.mypharmacy.mypharmacy;

public class ResumenPedido extends javax.swing.JFrame {
    private PharmacyForm parentFrame;
    

    public ResumenPedido(PharmacyForm parentFrame,String nombreMedicamento, String tipoMedicamento, int cantidadProducto, String distribuidor, String sucursal) {
        this.parentFrame = parentFrame;
        initComponents();
        
        this.setTitle("Pedido al distribuidor " + distribuidor );
        
        DatosPedido.setText(cantidadProducto + " unidades del " + tipoMedicamento + " " + nombreMedicamento);
        DireccionPedido.setText(sucursal);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        TitleForm = new javax.swing.JLabel();
        ImageTitleForm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tituloResumen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DireccionPedido = new javax.swing.JLabel();
        DatosPedido = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        BtnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resumen del pedido");
        setPreferredSize(new java.awt.Dimension(550, 360));
        getContentPane().setLayout(null);

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(550, 100));
        Header.setLayout(null);

        TitleForm.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TitleForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleForm.setText("PharmacyService");
        TitleForm.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TitleForm.setPreferredSize(new java.awt.Dimension(250, 24));
        Header.add(TitleForm);
        TitleForm.setBounds(94, 18, 408, 59);

        ImageTitleForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pharmacy.png"))); // NOI18N
        Header.add(ImageTitleForm);
        ImageTitleForm.setBounds(40, 18, 48, 59);

        getContentPane().add(Header);
        Header.setBounds(0, 0, 670, 100);

        jPanel2.setBackground(new java.awt.Color(214, 234, 248));
        jPanel2.setLayout(null);

        tituloResumen.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        tituloResumen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloResumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-purchase-order-30.png"))); // NOI18N
        tituloResumen.setText("Resumen Pedido:");
        jPanel2.add(tituloResumen);
        tituloResumen.setBounds(6, 16, 246, 61);

        jPanel1.setBackground(new java.awt.Color(214, 234, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 150));

        DireccionPedido.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DireccionPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DireccionPedido.setText("Para la direccion en D");
        DireccionPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DireccionPedido.setIconTextGap(2);

        DatosPedido.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        DatosPedido.setText("X unidades del T M");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DatosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addComponent(DireccionPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(DatosPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DireccionPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(-10, 10, 680, 150);

        jPanel3.setBackground(new java.awt.Color(214, 234, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cancel-40.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delivered-40.png"))); // NOI18N
        BtnEnviar.setText("Enviar Pedido");
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(BtnEnviar)
                .addGap(123, 123, 123)
                .addComponent(BtnCancelar)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEnviar)
                    .addComponent(BtnCancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 160, 670, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 670, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        System.out.println("Pedido enviado!");
        this.dispose();
        parentFrame.ResetForm();
        
       
       
    }//GEN-LAST:event_BtnEnviarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JLabel DatosPedido;
    private javax.swing.JLabel DireccionPedido;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel ImageTitleForm;
    private javax.swing.JLabel TitleForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tituloResumen;
    // End of variables declaration//GEN-END:variables
}
